### ISSUE TITLE
Mouse Position Accuracy

### ISSUE THREAD

**Issue by antable93** [JonahMonaghan/OverJoyed#5]
The virtual mouse (red dot) and mouse quadrant detection are inaccurate by a few pixels.

**Comment by JonahMonaghan** [comment]
Note that the detection is accurate to the mouse position but not the red dot's position

**Comment by JonahMonaghan** [comment]
> Note that the detection is accurate to the mouse position but not the red dot's position

I think

**Comment by antable93** [comment]
The form frame has a width of 1904 and height of 1041, so there is a left margin of 16 and top margin of 39. Form drawings were off by those amounts, so we need to make frame fullscreen.
